zone "cloudmatrix.local" {
    type slave;

    masters {
        192.168.10.10;
    };

    file "/var/cache/bind/slave.cloudmatrix.local";
};

zone "10.168.192.in-addr.arpa" {
    type slave;

    masters {
        192.168.10.10;
    };

    file "/var/cache/bind/slave.192.168.10";
};
