# CloudMatrix VM Reservations

host vm1 {
    hardware ethernet 00:11:22:33:44:01;
    fixed-address 192.168.10.101;
}

host vm2 {
    hardware ethernet 00:11:22:33:44:02;
    fixed-address 192.168.10.102;
}

host vm3 {
    hardware ethernet 00:11:22:33:44:03;
    fixed-address 192.168.10.103;
}

